export { apiClient, ApiClientError } from './api/client'
export { isSupabaseConfigured } from './supabase/client'
export { authService } from './authService'
export { destinationsService } from './destinations.service'
export { reviewsService } from './reviews.service'
export { favoritesService } from './favorites.service'
export { searchService } from './search.service'
export type { SearchResults } from './search.service'

// New scalable service layer exports
export { destinationService } from './destinationService'
export { provinceService } from './provinceService'
export { reviewService } from './reviewService'
export { favoriteService } from './favoriteService'
export { userService } from './userService'
export { feedService } from './feedService'
